subdir-ccflags-y := -Iinclude/kapi/phoenix -Iinclude/kapi/sh_kapi -Iinclude/kapi/sh_kapi/arch/$(ARCH)

obj-y	:= sh_sym_kapi.o
obj-y	+= sh_task_kapi.o
obj-y	+= sh_regs_kapi.o

obj-y	+= arch/$(ARCH)/