ccflags-y := -I$(srctree)/net/lwip-1.4.1/src/include \
			 -I$(srctree)/net/lwip-1.4.1/src/include/ipv4
obj-y += err.o
obj-y += sockets.o
obj-y += api_lib.o
obj-y += netbuf.o
obj-y += tcpip.o
obj-y += api_msg.o
obj-y += netifapi.o

