subdir-ccflags-y := -Iusr/include -Iusr/include/shell -Iusr/include/shell/arch/$(ARCH) -Iinclude/kapi/sh_kapi

obj-y	:= arch/$(ARCH)/

obj-y	+= sh_main.o
obj-y	+= sh_readline.o
obj-y	+= sh_keymap.o		
obj-y	+= sh_history.o
obj-y	+= sh_command.o
obj-y	+= sh_completion.o
obj-y	+= sh_filesystem.o
obj-y	+= sh_network.o
obj-y	+= sh_symbol.o
obj-y	+= sh_task.o
obj-y	+= sh_memory.o
obj-y	+= sh_register.o


