#!/bin/bash
#

TOP_DIR=$(dirname `readlink -f $0`)

. ${TOP_DIR}/lab-config

docker_image=$user/$name
local_lab_dir=$TOP_DIR/../
remote_lab_dir=/hot-pot-os/

CONTAINER_ID=""
[ -f $TOP_DIR/lab-container ] && CONTAINER_ID=$(< $TOP_DIR/lab-container)
[ -z "$CONTAINER_ID" ] && CONTAINER_ID=$(docker run -d -i -t --privileged=true -v $local_lab_dir:$remote_lab_dir $docker_image)
echo $CONTAINER_ID > $TOP_DIR/lab-container

docker start $CONTAINER_ID
docker attach $CONTAINER_ID
