obj-y   = dummy.o console.o pty.o vt.o keyboard.o consolemap.o tty_io.o selection.o \
		defkeymap.o n_tty.o tty_ioctl.o serial.o
#obj-y	+= serial.o tty_ioctl.o console.o pty.o vt.o keyboard.o consolemap.o tty_io.o selection.o \
#		defkeymap.o n_tty.o